{"version":3,"sources":["js/promise_3.js"],"names":["randomIntegerFromInterval","min","max","Math","floor","random","x","makeTransaction","transaction","console","log","delay","Promise","resolve","reject","setTimeout","id","amount","time","test","logSuccess","logError","warn","then","catch"],"mappings":";AAAA,aAmCA,IAAMA,EAA4B,SAACC,EAAKC,GAC7BC,OAAAA,KAAKC,MAAMD,KAAKE,UAAYH,EAAMD,EAAM,GAAKA,IAElDK,EAAI,gBACJC,EAAkB,SAACC,GACvBC,QAAQC,IAAIF,GAENG,IAAAA,EAAQX,EAA0B,KAAM,MAGvC,OAFPS,QAAQC,IAAIC,GAEL,IAAIC,QAAQ,SAACC,EAASC,GAC3BC,WAAW,WACUZ,KAAKE,SAAW,IAGjCQ,EAAQ,CAAEG,GAAIR,EAAYQ,GAAIC,OAAQT,EAAYS,OAAQC,KAAMP,EAAOQ,KAAMb,IAG/EQ,EAAON,EAAYQ,KAClBL,MAIDS,EAAa,SAA8B,GAA5BJ,IAAAA,EAAAA,EAAAA,GAAIC,EAAAA,EAAAA,OAAQC,EAAAA,EAAAA,KAAMC,EAAAA,EAAAA,KACrCV,QAAQC,IAAmBM,eAAAA,OAAAA,EAAeC,cAAAA,OAAAA,EAAuBC,kBAAAA,OAAAA,EAC1DC,gBAAAA,OAAAA,KAGHE,EAAW,SAAAL,GACfP,QAAQa,KAAqCN,gCAAAA,OAAAA,EAA7C,+BAGFT,EAAgB,CAAES,GAAI,GAAIC,OAAQ,MAAOM,KAAKH,GAAYI,MAAMH,GAChEd,EAAgB,CAAES,GAAI,GAAIC,OAAQ,MAAOM,KAAKH,GAAaI,MAAMH,GACjEd,EAAgB,CAAES,GAAI,GAAIC,OAAQ,KAAMM,KAAKH,GAAaI,MAAMH,GAChEd,EAAgB,CAAES,GAAI,GAAIC,OAAQ,MAAOM,KAAKH,GAAYI,MAAMH","file":"promise_3.b3350e9e.js","sourceRoot":"../src","sourcesContent":["'use strict'\n\n// const randomIntegerFromInterval = (min, max) => {\n//     return Math.floor(Math.random() * (max - min + 1) + min);\n// };\n\n// const makeTransaction = (transaction, onSuccess, onError) => {\n//     const delay = randomIntegerFromInterval(200, 500);\n//     setTimeout(() => {\n//         const canProcess = Math.random() > 0.3;\n\n// if (canProcess) {\n//   onSuccess(transaction.id, delay);\n// } else {\n//   onError(transaction.id);\n// }\n// }, delay); };\n\n// const logSuccess = (id, time) => {\n//   console.log(`Transaction ${id} processed in ${time} ms`);\n// };\n\n// const logError = id => {\n//   console.warn(`Error processing transaction ${id}. Please try again later.`);\n// };\n\n// /*Работает так */ \n// makeTransaction({ id: 70, amount: 150 }, logSuccess, logError);\n// makeTransaction({ id: 71, amount: 230 }, logSuccess, logError);\n// makeTransaction({ id: 72, amount: 75 }, logSuccess, logError);\n// makeTransaction({ id: 73, amount: 100 }, logSuccess, logError); \n\n//========================================================================\n/*Должно работать так */\n\nconst randomIntegerFromInterval = (min, max) => {\n    return Math.floor(Math.random() * (max - min + 1) + min);\n};\nconst x = '\"test_string\"'\nconst makeTransaction = (transaction) => {\n  console.log(transaction);\n  \n  const delay = randomIntegerFromInterval(1200, 3500);\n  console.log(delay);\n  \n  return new Promise((resolve, reject) => {\n    setTimeout(() => {\n      const canProcess = Math.random() > 0.3;\n\n      if (canProcess) {\n        resolve({ id: transaction.id, amount: transaction.amount, time: delay, test: x });\n        //console.log(resolve);\n      }\n      reject(transaction.id);\n    }, delay);\n  })\n};    \n\nconst logSuccess = ({id, amount, time, test}) => { //выполнена деструктуризация объекта\n  console.log(`Transaction ${id} with sum ${amount} processed in ${time} ms\n   and ${test}`);\n};\n\nconst logError = id => {\n  console.warn(`Error processing transaction ${id}. Please try again later.`);\n};\n\nmakeTransaction({ id: 70, amount: 150 }).then(logSuccess).catch(logError);\nmakeTransaction({ id: 71, amount: 230 }).then(logSuccess) .catch(logError);\nmakeTransaction({ id: 72, amount: 75 }).then(logSuccess) .catch(logError);\nmakeTransaction({ id: 73, amount: 100 }).then(logSuccess).catch(logError);\n\n//=========================================================================\n// const promise = new Promise((resolve, reject) => {\n//   setTimeout(() => {\n//     /*\n//      * Если какое-то условие выполняется, то есть все хорошо,\n//      * вызываем resolve и получает данные. Условие зависит от задачи.\n//      */\n//     resolve('Data passed into resolve function :)');\n\n//     // Если что-то не так, вызываем reject и передаем ошибку\n//     //reject(\"Error passed into reject function :(\")\n//   }, 2000);\n// });\n\n// // Выполнится мгновенно\n// console.log('BEFORE promise.then');\n\n// const onResolve = data => {\n//   console.log(data); // \"Data passed into resolve function :)\"\n//   console.log('INSIDE promise.then - onResolve');\n// };\n\n// const onReject = error => {\n//   console.log('INSIDE promise.then - onReject');\n//   console.log(error); // \"Error passed into reject function :(\"\n// };\n\n// promise.then(\n//   // будет вызвана через 2 секунды, если обещание выполнится успешно\n//   onResolve,\n//   // будет вызвана через 2 секунды, если обещание выполнится с ошибкой\n//   onReject,\n// );\n\n// // Выполнится мгновенно\n// console.log('AFTER promise.then');\n"]}